### ISSUE TITLE
Using latest released version fails with 'proto_common_do_not_use' is not defined

### ISSUE THREAD

**Issue by cristifalcas** [bazelbuild/rules_proto#160]
Using latest released version (`rules_proto 5.3.0-21.5`) fails:

```
ERROR: /private/var/tmp/_bazel_cfalcas/856dc74a4318774eeb1496e4c7291b94/external/rules_proto/proto/private/native.bzl:28:23: name 'proto_common_do_not_use' is not defined
```

Should `proto_common_do_not_use` be quoted [here](https://github.com/bazelbuild/rules_proto/blob/b5e5fc85f70cf6bbef66c69b679c86168ad1bea6/proto/private/native.bzl#L28)? I don't understand where it's used.

**Comment by bcsgh** [comment]
I was getting that until I updated Bazel from 5.1.1 to 6.0.0

----

But then I ran into a different issue; https://github.com/bazelbuild/rules_proto/issues/153 

To fix that I think https://github.com/bazelbuild/rules_proto/commit/f371ed34ed7f1a8b83cc34ae96db277e0ba4fcb0 needs to be cherry-picked (i.e. use `git_repository()` at that commit rather than `http_archive()`).

**Comment by comius** [comment]
The name of the release suggests to use baze at least 5.3.0. Second issue with hash was fixed.
