### ISSUE TITLE
Project Health Question: Is this project still maintained and recommended?

### ISSUE THREAD

**Issue by hagbard** [bazelbuild/rules_proto#176]
I see quite a lot of serious looking issues in this project for which no resolution is being discussed.
I also note that the build is currently broken (and has been for a while).

Is this project still the "recommended" way to deal with protocol buffers in Bazel, or has something else replaced it?

**Comment by comius** [comment]
`rules_proto` is at the moment mostly empty and contains stubs for `proto_library`, `ProtoInfo` and other proto toolchain support rules. That's the reason we don't prioritise on its mainteinance.

This will change in the future after Bazel 7 is released (in Oct/Nov 2023), because the stubs will be replaced with actual implementations. The implementation won't be available in Bazel 8.

As such it's recommended to use this repository, so that the removal of implementations from Bazel 8 does not cause you problems.

Also:
- I addressed and triaged all the issues in the project.
- I fixed the build at head.
