### ISSUE TITLE
Implement proto toolchainisation

### ISSUE THREAD

**Issue by comius** [bazelbuild/rules_proto#179]
Design document: https://docs.google.com/document/d/1CE6wJHNfKbUPBr7-mmk_0Yo3a4TaqcTPE0OWNuQkhPs/edit#heading=h.5mcn15i0e1ch

**Comment by alexeagle** [comment]
@comius can you assign to @thesayyn - we are going to start on this pretty soon.

**Comment by comius** [comment]
cc @fowles, @haberman

I've sent invite to @thesayyn, @alexeagle.

There's quite some stuff that needs to be coordinated internally, I'll start pushing out changes.

**Comment by alexeagle** [comment]
Hm, I don't see any invites from GitHub...

**Comment by comius** [comment]
Hey, @alexeagle and @thesayyn, is there any progress on this? Any problems/issues/blockers?

I'm still waiting for reviews internally. The reviewer is out till Wednesday.

**Comment by alexeagle** [comment]
This bit me again because rules_ts [accidentally needs](https://github.com/aspect-build/rules_ts/pull/531) a C++ toolchain just for `protoc`. 

I'd like to send a PR to add a "pre-built binary toolchain" for `protoc` here.

The approach will be:
- Provide users with a "binary" toolchain where they can supply protoc download information.
- Accept that we'll have a file in rules_proto listing some versions of protoc along with the integrity hash per-platform.
- Add a GitHub Actions automation to send us PRs whenever a new `protoc` version is released to https://github.com/protocolbuffers/protobuf/releases
- Example script mirroring https://github.com/astral-sh/ruff/releases is here: https://github.com/aspect-build/rules_lint/blob/main/lint/mirror_ruff.sh
- The resulting PR is trivial to approve and merge, like https://github.com/aspect-build/rules_lint/pull/108
- We add an additional toolchain registration API users can use to select these pre-built binaries.
- Maybe in a later release, this becomes the default `protoc` toolchain, so users stop having to compile it from source.

**Comment by alexeagle** [comment]
FYI @comius I'm implementing that proposal now. From interaction with the protobuf repo around publishing to BCR, I think it's clear that maintainers over there shouldn't be tasked with publishing a Bazel module.
