### ISSUE TITLE
Add //examples

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_proto#18]
It would be useful to add/link to examples of use of the rules proto.

**Comment by Yannic** [comment]
For now, we'll use https://blog.bazel.build/2017/02/27/protocol-buffers.html (https://github.com/bazelbuild/bazel-blog/pull/191) and https://github.com/cgrushko/proto_library as examples. I'll update the readme accordingly.

/label `documentation`, `enhancement` 
/assign @Yannic

**Comment by hlopko** [comment]
To be the Captain Obvious, these examples should be buildable and tested on the CI.

**Comment by abhillman** [comment]
+1

**Comment by alexeagle** [comment]
I don't think rules_proto should ever contain "an example in every language" because we don't know how to setup Bazel rules for every language and it will surely go horribly out-of-date.
I think examples should either live in the language ruleset (e.g. py_proto_library example in rules_python) and/or in the github.com/bazelbuild/examples repository.
