### ISSUE TITLE
Avoid passing both the short and the long proto paths to protoc

### ISSUE THREAD

**Issue by iirina** [bazelbuild/rules_proto#58]
Currently for each `.proto` file Bazel passes to `protoc` the path relative to the workspace (the *long path*) via `-I` flag (alias for `--proto_path`).

Since 15a4362, Bazel also passes to `protoc` a *short path* via the `--proto_path` flag. The short path is only passed for `proto_library` targets that have set `proto_source_root`.

Passing to `protoc` both the *short* and the *long* path to a `.proto` file is error prone. A better mechanism must be implemented to deal with these situations.

**Comment by Yannic** [comment]
A lot has changed since 2018 (e.g. the aforementioned `proto_source_root` has since been removed), so I'm not sure if this is still an issue.

There's also work going on to change how `.proto` files are compiled (e.g. bazelbuild/bazel#10939, bazelbuild/bazel#1005), which will definitely fix this (in case it isn't already fixed).

**Comment by Yannic** [comment]
Fixed in  bazelbuild/bazel#10939
